open:
  storage:
    remote:
      - firestore
    local:
      - shared_preferences
      - database?
  
  authentification:
    - firebase auth

  game:
    get_players:
      manally:
        - String entrys
      automatically:
        - link share via social
        - qr-code on-screen
        - invite friends in-app

  platforms:
    web:
      github pages:
        - klasl4243.github.io/rote20_gewinnt
        - enforce https
      domain:
        - dorfserver.com
        - rote20-gewinnt.de?

    android:
      playstore:
        - deploy to playstore
        - register developer account
    
    ios:
      appstore:
        - deploy to appstore
        - register developer account

  github:
    - secrets:
      - key files
      - environment variables
