name: rote20_gewinnt
description: "A new Flutter project." # TODO: add description 
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1
  #flutter_localizations:
  #  sdk: flutter
  intl: ^0.19.0

  # TODO: app package dependencies here
  app_api:
    path: packages/app_api

  shared_preferences: ^2.2.3

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.7


flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  #arb_dir: lib/l10n # default: lib/l10n/
  output_dir: lib/l10n # default: lib/generated
