name: login_api
description: "TODO: add description"
version: 0.0.1+1
homepage:

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  meta: ^1.12.0
  uuid: ^3.0.7

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
