name: game_repository
description: "" #TODO: add description
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  game_api:
    path: ../game_api

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.21.4
